---
title: "Informe sobre aislamientos"
author: "Medicina Preventiva HUC"
date: '2022-06-07'
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, warning=FALSE}

#SCRIPT PARA informe de centinela, JUNIO 2022---------------------------------

library(pacman)

pacman:: p_load(tidyverse,
                googlesheets4,           #leer pase de guardia
                gtsummary,               #hacer tablas
                lubridate,               #editar fechas
                flextable,               #edicion de tablas
                ggplot2,                 #para los graficos
                readxl,
                devtools,                #para editar graficos
                writexl,                 #exportar excel
                janitor,                 #limpieza de datos avanzada
                readxlsb,                #archivos de la torre
                openxlsx,
                skimr,
                rio,
                ggpubr,                  #juntar dos graficos en uno
                knitr,
                gt,
                kableExtra
                #RDCOMClient,            #VBA
)

#CAMBIOS MANUALES



# poner el primer dia de la semana a analizar

l_1 <- Sys.Date() - weeks(2) 

limite <- floor_date(l_1,
                     unit = "week",
                     week_start = 1) - 6 


#limite <- "2022-06-05"-----------por si se quiere ponerla semana  manualmente


#CARGAR DATOS------------------------------------------------------------------------------------
setwd("C:/Users/kl_93/OneDrive/Escritorio/cruces/centinela")

data <- import("koldo.xlsx") %>% 
  clean_names() %>% 
  as_tibble() 



# ME QUEDO CON LOS DE LA SEMANA ANTERIOR--------------------------------------------------------

data_limpio <-  data %>% 
  
  mutate(
    across(.cols = where(is.POSIXct), .fns = as.Date),
    
    edad = ((Sys.Date()- fecha_de_nacimiento)/365),
    edad_numeric = as.numeric(edad),
    edad_categorias = case_when(
      edad_numeric                      <  10  ~ "00-09",
      edad_numeric > 9 & edad_numeric < 20 ~ "10-19",
      edad_numeric > 19 & edad_numeric < 30 ~ "20-29",
      edad_numeric > 29 & edad_numeric < 40 ~ "30-39",
      edad_numeric > 39 & edad_numeric < 50 ~ "40-49",
      edad_numeric > 49 & edad_numeric < 60 ~ "50-59",
      edad_numeric > 59 & edad_numeric < 70 ~ "60-69",
      edad_numeric > 69 & edad_numeric < 80 ~ "70-79",
      edad_numeric > 79 & edad_numeric < 90 ~ "80-89",
      edad_numeric > 89 ~ ">90"),
    
    edad_categorias = factor(
      edad_categorias,
      level = c("00-09", "10-19", "20-29",
                "30-39", "40-49", "50-59",
                "60-69","70-79", "80-89",
                ">90")),
    
    
    #variables utiles: semana_nuevos y con LETRAS, AUTOMATICO-----------
    
    semana_nuevos = floor_date(fecha_inicio_aisl,
                               unit = "week",
                               week_start = 1),
    
    
    semana_nuevos_letras = floor_date(fecha_inicio_aisl,
                            unit = "week",
                            week_start = 1),
      
      
      
    semana_nuevos_letras_2 = floor_date(fecha_inicio_aisl,
                            unit = "week",
                            week_start = 1) + 6,
      
    semana_nuevos_letras = format( semana_nuevos_letras, "%d%b"),
    semana_nuevos_letras_2 = format( semana_nuevos_letras_2, "%d%b")) %>% 
    unite(col = "semana_nuevos_letras", c("semana_nuevos_letras", "semana_nuevos_letras_2"), sep = "/ ", remove = T) %>% 
     
  
  #----------------------------  
    mutate(   
    
    semana_final_aislamiento = floor_date(fecha_final_aisl,
                                          unit = "week",
                                          week_start = 1),
    
    dias_ingreso_registro =    fecha_registro    - fecha_de_ingreso,
    dias_ingreso_aislamiento = fecha_inicio_aisl - fecha_de_ingreso,
    
    #legibilidad
    
    germen = tolower(germen),
    germen = str_to_title(germen),
    
    precauciones = tolower(precauciones),
    precauciones = str_to_title(precauciones),
    
    sexo = case_when(
      sexo == 0 ~ "Hombre",
      sexo == 1 ~ "Mujer"),
    
    tipo  = case_when(
      tipo == 1 ~ "Nosocomial",
      tipo == 2 ~ "Comunitaria",
      tipo == 3 ~ "Reingreso nosocomial",
      tipo == 4 ~ "Incierto",
      tipo == 5 ~ "Reingreso comunitaria",
      tipo == 6 ~ "Asociada a cuidados"),
    
    id_procedencia = case_when(
      id_procedencia ==    1  ~	"ANESTESIA REANIMACIÓN",
      id_procedencia ==    2  ~	"C. INF. SECCIÓN ORTOPEDIA",
      id_procedencia ==    3  ~	"C.INF. SECCIÓN UROLÓGIA",
      id_procedencia ==    4  ~	"C. CARDIACA",
      id_procedencia ==    5  ~	"C.GENERAL A",
      id_procedencia ==    6  ~	"C. GENERAL B",
      id_procedencia ==    7  ~	"C. INF. SECCIÓN A",
      id_procedencia ==    8  ~	"C. INF. SECCIÓN B",
      id_procedencia ==    9  ~	"C. INF. SECCIÓN C",
      id_procedencia ==    10 ~	"C. INF. SECCIÓN ORL",
      id_procedencia ==    11 ~ "C. MAXILOFACIAL",
      id_procedencia ==    12 ~	"C. PLÁSTICA",
      id_procedencia ==    13 ~	"C. PLÁSTICA - G. QUEMADOS",
      id_procedencia ==    14 ~	"C. TORÁCICA",
      id_procedencia ==    15 ~	"C. VASCULAR",
      id_procedencia ==    16 ~	"CARDIOLOGÍA",
      id_procedencia ==    17 ~	"CARDIOLOGÍA INFANTIL",
      id_procedencia ==    18 ~	"ENDOCRINOLOGÍA",
      id_procedencia ==    19 ~	"GASTROENTEROLOGÍA",
      id_procedencia ==    20 ~	"GINECOLOGÍA",
      id_procedencia ==    21 ~	"GINECOLOGÍA - ONCOLOGÍA",
      id_procedencia ==    22 ~	"HEMATOLOGÍA",
      id_procedencia ==    23 ~	"M. INTERNA",
      id_procedencia ==    24 ~	"M. INTENSIVA",
      id_procedencia ==    25 ~	"NEFROLOGÍA",
      id_procedencia ==    26	~"NEFROLOGÍA INFANTIL",
      id_procedencia ==    27 ~	"NEUMOLOGÍA",
      id_procedencia ==    28 ~	"NEUROCIRUGÍA",
      id_procedencia ==    29 ~	"NEUROLOGÍA",
      id_procedencia ==    30	~"NEUROPEDIATRÍA",
      id_procedencia ==    31 ~	"O.R.L.",
      id_procedencia ==    32 ~	"OBSTETRICIA",
      id_procedencia ==    33 ~	"OFTALMOLOGÍA",
      id_procedencia ==    34 ~	"ONCOLOGÍA INFANTIL",
      id_procedencia ==    35 ~	"ONCOLOGÍA MÉDICA",
      id_procedencia ==    36 ~	"ONCOLOGÍA RADIOTERÁPICA",
      id_procedencia ==    37 ~	"PEDIATRÍA CUIDADOS INTENSIVOS",
      id_procedencia ==    38 ~	"PEDIATRÍA GENERAL",
      id_procedencia ==    39 ~	"PSIQUIATRÍA",
      id_procedencia ==    40	~ "PSIQUIATRÍA INFANTIL",
      id_procedencia ==    41 ~	"REHABILITACIÓN",
      id_procedencia ==    42	~ "REUMATOLOGÍA",
      id_procedencia ==    43	~ "TRAUMATOLOGÍA",
      id_procedencia ==    44	~ "U. ENF. INFECCIOSAS",
      id_procedencia ==    45	~ "UNIDAD CORONARIA",
      id_procedencia ==    46	~ "UNIDAD NEONATAL",
      id_procedencia ==    47 ~	"UROLOGÍA",
      id_procedencia ==    48	~ "U.C.HEPATICA",
      id_procedencia ==    49	~ "URGENCIAS MEDICO-QUIRURGICAS",
      id_procedencia ==    50 ~	"EXTRAHOSPITALARIO",
      id_procedencia ==    51 ~	"HOSPITALARIO",
      id_procedencia ==    52 ~	"REINGRHOSPITALARIO",
      id_procedencia ==    53 ~	"REINGREXTRAHOSPITALARIO"))%>% 
      
  mutate_if(is.numeric, round, digits=0) %>% 
  
  #quitamos covid que genera ruido
    filter(germen != "Coronavirus Sars-Cov-2" &
           germen != "Adenovirus" &
           germen != "Astrovirus" &
           germen != "Bocavirus" &
           germen != "Coronavirus" &
           germen != "Coxsackie" &
           germen != "Echovirus" &
           germen != "Enterovirus" &
           germen != "Herpes Simplex I" &
           germen != "Herpes Simplex Ii" &
           germen != "Herpes Zoster" &
           germen != "Metapneumovirus" &
           germen != "Monkeypox" &
           germen != "Norovirus"&  
           germen != "Parechovirus"&
           germen != "Parvovirus B19"&
           germen != "Rabia Virus"&
           germen != "Rhinovirus"&
           germen != "Rotavirus"&
           germen != "Varicela-Zoster") %>% 
  
  filter(!grepl("Influenza|Parainfluenza|Virus|Vrs", germen)) %>% 
         #germen != "Influenza A" |
         #germen !=  grepl("Parainfluenza", germen) |
         #germen !grepl("Virus", germen) |
         #germen !=  grepl("Vrs", germen)) %>% 
  
  select(-c(orden, edad, fecha_de_nacimiento, no_ha_ca, conexion)) %>% 
  arrange(germen) %>% 
  
  #LIMPIEZA DE LAS HABITACIONES
  mutate( 
    id_habitacion_copia = id_habitacion,
    id_habitacion = gsub(pattern = "-", replacement = ".", id_habitacion, fixed = TRUE),
    id_habitacion = gsub(pattern = ",", replacement = ".", id_habitacion, fixed = TRUE),
    
    
    #las Ts son 33
    id_habitacion = gsub(pattern = "N", replacement = "22", id_habitacion, fixed = TRUE),
    id_habitacion = gsub(pattern = "C", replacement = "12", id_habitacion, fixed = TRUE),
    id_habitacion = gsub(pattern = "T", replacement = "33", id_habitacion, fixed = TRUE),
    id_habitacion = gsub(pattern = "M", replacement = "11", id_habitacion, fixed = TRUE),
    id_habitacion = gsub(pattern = "H", replacement = "14", id_habitacion, fixed = TRUE),
    
    #esto para las camas de la 650
    id_habitacion = gsub(pattern = "A", replacement = "12", id_habitacion, fixed = TRUE),
    
    #y aqui ya lo convierto en numerico
    id_habitacion_planta = as.numeric(id_habitacion),
    
    id_habitacion_planta = if_else(id_habitacion_planta > 7000, 0 , id_habitacion_planta),
    id_habitacion_planta = if_else( id_habitacion_planta > 6000 & id_habitacion_planta < 7000, id_habitacion_planta-6012, id_habitacion_planta))%>% 
  
  #nombres de plantas
  mutate(
    cama = as.numeric(id_habitacion_planta),
    planta = case_when(
      cama > 99  & cama <125 ~ "1A",
      #las Ms
      cama > 1099  & cama <1150 ~ "1A",
      cama > 124 & cama <150 ~ "1B",
      #las Hs
      cama > 1399  & cama <1499 ~ "1A",
      cama > 149 & cama <175 ~ "1D",
      cama > 174 & cama <200 ~ "1E",
      cama > 199 & cama <225 ~ "2A",
      #las Ns
      cama > 2199  & cama <2250 ~ "2A",
      cama > 224 & cama <250 ~ "2B",
      cama > 249 & cama <275 ~ "2D",
      cama > 274 & cama <300 ~ "2E",
      cama > 299 & cama <325 ~ "3A",
      #las Ts
      cama > 3299  & cama <3350 ~ "3A",
      cama > 324 & cama <350 ~ "3B",
      cama > 349 & cama <375 ~ "3D",
      cama > 374 & cama <400 ~ "3E",
      cama > 399 & cama <425 ~ "4A",
      cama > 424 & cama <450 ~ "4B",
      cama > 449 & cama <475 ~ "4D",
      cama > 474 & cama <500 ~ "4E",
      cama > 499 & cama <525 ~ "5A",
      cama > 524 & cama <550 ~ "5B",
      cama > 549 & cama <575 ~ "5D",
      cama > 574 & cama <600 ~ "5E",
      cama > 599 & cama <625 ~ "6A",
      cama > 624 & cama <650 ~ "6B",
      cama > 649 & cama <675 ~ "6D",
      cama > 674 & cama <700 ~ "6E",
      cama > 699 & cama <750 ~ "7",
      cama > 1199 & cama <1250 ~ "12"))

#data_limpio %>% select(germen) %>% tbl_summary()

#NUEVOS--------------------------------------------------------------------------------


#aqui meto el limite
nuevos <-  data_limpio %>% 
  filter(semana_nuevos > limite) 

nuevos_tabla <- nuevos %>% 
  select(germen, precauciones, tipo) %>% 
  mutate(tipo = if_else(tipo == "Reingreso comunitaria", "Comunitaria", tipo)) %>% 
  arrange(germen, precauciones) %>% 
  tbl_summary(
    by = tipo,
    sort = list(
    germen ~ "frequency",
    precauciones ~ "frequency")) %>% 
  bold_labels()

nosocomiales_tabla_nuevos <- nuevos %>% 
  filter(grepl("Nosocomial|Reingreso nosocomial|Incierto", tipo)) %>% 
  select(cic, nombre, apellidos, germen, edad_categorias, planta, id_procedencia, tipo) %>% 
  arrange(germen, planta) %>% 
  gt()%>% 
  #añadir bordes
  tab_style(
   style =  cell_borders(
      sides = c("left", "right", "top", "bottom"),
      color = "black",
      style = "solid"),
   locations = cells_body(
     columns = everything())) %>% 
  #enfatizar las titulos
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style     = list(
      #Give a thick border below
      cell_borders(sides = "bottom", weight = px(3)),
      #Make text bold
      cell_text(weight = "bold"))) %>% 
  opt_table_font(
        font = list(
          google_font("Chivo"),
          default_fonts()
        )
      ) 

#aqui preparar un listado para el anexo. Tengo que quitar varias columnas
#view(nuevos)

#INDICADOR DE NUEVAS APARICIONES..........................................

l1 <-  Sys.Date()

limite_indicador <- floor_date(l_1,
                     unit = "week",
                     week_start = 1) - 84
  


#STENOTROPHOMONAS MALTOPHILIA-----------------------------------

indicador_marga_steno <- data_limpio %>% 
  filter(semana_nuevos > limite_indicador & germen == "Stenotrophomonas Maltophilia") %>% 
  mutate(
    semana_nuevos_letras = as.factor(semana_nuevos_letras),
    semana_nuevos_letras = fct_reorder(semana_nuevos_letras, semana_nuevos, min)) %>% 
  select(semana_nuevos_letras, planta, cic) %>% 
  #mutate(germen = 1) %>% 
  pivot_wider(names_from = semana_nuevos_letras, values_from = cic) %>% 
  arrange(planta) %>% 
  gt()%>% 
  #añadir bordes
  tab_style(
   style =  cell_borders(
      sides = c("left", "right", "top", "bottom"),
      color = "black",
      style = "solid"),
   locations = cells_body(
     columns = everything())) %>% 
  #enfatizar las titulos
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style     = list(
      #Give a thick border below
      cell_borders(sides = "bottom", weight = px(3)),
      #Make text bold
      cell_text(weight = "bold"))) %>% 
  opt_table_font(
        font = list(
          google_font("Chivo"),
          default_fonts()
        )
      ) 

#ENTEROBACTER------------------------

indicador_marga_enterobac_previo <- data_limpio %>% 
  filter(semana_nuevos > limite_indicador & germen == "Enterobacter Productor De Carbapenemasas") %>% 
  select(semana_nuevos, germen, cic, planta, semana_nuevos_letras)

limite_bajo <- min(indicador_marga_enterobac_previo$semana_nuevos)
limite_alto <- max(indicador_marga_enterobac_previo$semana_nuevos)


tabla_limites <- data.frame(semana_nuevos = seq(as.Date(limite_bajo), as.Date(limite_alto), by="weeks"),
                            germen = "Enterobacter Productor De Carbapenemasas",
                            cic = " ",
                            planta = "HUC-SMP") %>% 
  as.tibble() %>% 
  mutate(semana_nuevos_letras = floor_date(semana_nuevos,
                                           unit = "week",
                                           week_start = 1),
         
         
         semana_nuevos_letras_2 = floor_date(semana_nuevos,
                                             unit = "week",
                                             week_start = 1) + 6,
         
         semana_nuevos_letras = format( semana_nuevos_letras, "%d%b"),
         semana_nuevos_letras_2 = format( semana_nuevos_letras_2, "%d%b")) %>% 
  unite(col = "semana_nuevos_letras", c("semana_nuevos_letras", "semana_nuevos_letras_2"), sep = "/ ", remove = T)



indicador_marga_enterobac <- rbind(indicador_marga_enterobac_previo, tabla_limites) %>% 
  mutate(
    semana_nuevos_letras = as.factor(semana_nuevos_letras),
    semana_nuevos_letras = fct_reorder(semana_nuevos_letras, semana_nuevos, min)) %>% 
  select(semana_nuevos_letras, planta, cic) %>% 
  #lo ordeno previamente porque pivot_wide no respeta los factores, solo el orden de aparicion
  #entonces las dos lineas previas de codigo sobrarian
  arrange(semana_nuevos_letras) %>% 
  #mutate(germen = 1) %>% 
  pivot_wider(names_from = semana_nuevos_letras, values_from = cic) %>% 
  arrange(planta) %>% 
  gt() %>% 
  #añadir bordes
  tab_style(
    style =  cell_borders(
      sides = c("left", "right", "top", "bottom"),
      color = "black",
      style = "solid"),
    locations = cells_body(
      columns = everything())) %>% 
  #enfatizar las titulos
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style     = list(
      #Give a thick border below
      cell_borders(sides = "bottom", weight = px(3)),
      #Make text bold
      cell_text(weight = "bold"))) %>% 
  opt_table_font(
    font = list(
      google_font("Chivo"),
      default_fonts()
    )
  ) 

#PSEUDOMONAS-----------------------------------------

indicador_marga_pseudomona_previo <- data_limpio %>% 
  filter(semana_nuevos > limite_indicador) %>% 
  filter(grepl("Pseudomonas", germen)) %>% 
  select(semana_nuevos, germen, cic, planta, semana_nuevos_letras)

limite_bajo <- min(indicador_marga_pseudomona_previo$semana_nuevos)
limite_alto <- max(indicador_marga_pseudomona_previo$semana_nuevos)


tabla_limites <- data.frame(semana_nuevos = seq(as.Date(limite_bajo), as.Date(limite_alto), by="weeks"),
                            germen = "Pseudomonas",
                            cic = " ",
                            planta = "HUC-SMP") %>% 
  as.tibble() %>% 
  mutate(semana_nuevos_letras = floor_date(semana_nuevos,
                                           unit = "week",
                                           week_start = 1),
         
         
         semana_nuevos_letras_2 = floor_date(semana_nuevos,
                                             unit = "week",
                                             week_start = 1) + 6,
         
         semana_nuevos_letras = format( semana_nuevos_letras, "%d%b"),
         semana_nuevos_letras_2 = format( semana_nuevos_letras_2, "%d%b")) %>% 
  unite(col = "semana_nuevos_letras", c("semana_nuevos_letras", "semana_nuevos_letras_2"), sep = "/ ", remove = T)



indicador_marga_pseudomona <- rbind(indicador_marga_pseudomona_previo, tabla_limites) %>% 
  mutate(
    semana_nuevos_letras = as.factor(semana_nuevos_letras),
    semana_nuevos_letras = fct_reorder(semana_nuevos_letras, semana_nuevos, min)) %>% 
  select(semana_nuevos_letras, planta, cic) %>% 
  #lo ordeno previamente porque pivot_wide no respeta los factores, solo el orden de aparicion
  #entonces las dos lineas previas de codigo sobrarian
  arrange(semana_nuevos_letras) %>% 
  #mutate(germen = 1) %>% 
  pivot_wider(names_from = semana_nuevos_letras, values_from = cic) %>% 
  arrange(planta) %>% 
  gt() %>% 
  #añadir bordes
  tab_style(
    style =  cell_borders(
      sides = c("left", "right", "top", "bottom"),
      color = "black",
      style = "solid"),
    locations = cells_body(
      columns = everything())) %>% 
  #enfatizar las titulos
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style     = list(
      #Give a thick border below
      cell_borders(sides = "bottom", weight = px(3)),
      #Make text bold
      cell_text(weight = "bold"))) %>% 
  opt_table_font(
    font = list(
      google_font("Chivo"),
      default_fonts()
    )
  ) 

#SARM-------------------------------------


indicador_marga_sarm_previo <- data_limpio %>% 
  filter(semana_nuevos > limite_indicador & germen == "Sarm") %>% 
  select(semana_nuevos, germen, cic, planta, semana_nuevos_letras)

limite_bajo <- min(indicador_marga_sarm_previo$semana_nuevos)
limite_alto <- max(indicador_marga_sarm_previo$semana_nuevos)


tabla_limites <- data.frame(semana_nuevos = seq(as.Date(limite_bajo), as.Date(limite_alto), by="weeks"),
                            germen = "Sarm",
                            cic = " ",
                            planta = "HUC-SMP") %>% 
  as.tibble() %>% 
  mutate(semana_nuevos_letras = floor_date(semana_nuevos,
                                           unit = "week",
                                           week_start = 1),
         
         
         
         semana_nuevos_letras_2 = floor_date(semana_nuevos,
                                             unit = "week",
                                             week_start = 1) + 6,
         
         semana_nuevos_letras = format( semana_nuevos_letras, "%d%b"),
         semana_nuevos_letras_2 = format( semana_nuevos_letras_2, "%d%b")) %>% 
  unite(col = "semana_nuevos_letras", c("semana_nuevos_letras", "semana_nuevos_letras_2"), sep = "/ ", remove = T)



indicador_marga_sarm <- rbind(indicador_marga_sarm_previo, tabla_limites) %>% 
  mutate(
    semana_nuevos_letras = as.factor(semana_nuevos_letras),
    semana_nuevos_letras = fct_reorder(semana_nuevos_letras, semana_nuevos, min)) %>% 
  select(semana_nuevos_letras, planta, cic) %>% 
  #lo ordeno previamente porque pivot_wide no respeta los factores, solo el orden de aparicion
  #entonces las dos lineas previas de codigo sobrarian
  arrange(semana_nuevos_letras) %>% 
  #mutate(germen = 1) %>% 
  pivot_wider(names_from = semana_nuevos_letras, values_from = cic) %>% 
  arrange(planta) %>% 
  gt() %>% 
  #añadir bordes
  tab_style(
    style =  cell_borders(
      sides = c("left", "right", "top", "bottom"),
      color = "black",
      style = "solid"),
    locations = cells_body(
      columns = everything())) %>% 
  #enfatizar las titulos
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style     = list(
      #Give a thick border below
      cell_borders(sides = "bottom", weight = px(3)),
      #Make text bold
      cell_text(weight = "bold"))) %>% 
  opt_table_font(
    font = list(
      google_font("Chivo"),
      default_fonts()
    )
  ) 



#ACTIVOS-------------------------------------------------------------------------------

activos <- data_limpio %>% 
  filter(is.na(fecha_final_aisl)) %>% 
  filter(is.na(fecha_de_alta)) %>% 
  filter(aislamiento == 1) %>% 
  select(-c(fecha_de_alta,id_destino_de_alta))


activos_tabla <- activos %>% 
  select(germen, precauciones, tipo) %>% 
  arrange(germen, precauciones) %>% 
  tbl_summary(
    by = tipo,
    sort = list(everything() ~ "frequency")
  ) %>% 
  bold_labels()





#FINALIZADOS-----------------------------------------------------------------------



finalizados <- data_limpio %>% 
  filter(semana_final_aislamiento > limite) 


finalizados_tabla <- finalizados %>% 
  select(fecha_final_aisl, germen, precauciones) %>% 
  arrange(germen, precauciones) %>% 
  tbl_summary(
    sort = list(germen ~ "frequency",
                precauciones ~ "frequency")) %>% 
  bold_labels()

#REVISAR

habitas_por_mirar <- data_limpio %>%
  filter(is.na(planta) & !is.na(id_habitacion) & semana_nuevos > "2022-01-01") %>% 
  select(cic, id_habitacion) %>% 
  gt()



```

# Nuevos aislamientos de los últimos 20 días

```{r, echo=FALSE, message=FALSE, warning=FALSE}

nuevos_tabla


```

\
\
\

# Tabla de pacientes con aislamientos nosocomiales

```{r, echo=FALSE, message=FALSE, warning=FALSE}

nosocomiales_tabla_nuevos


```

\
\
\

# Aislamientos activos

```{r, echo=FALSE, message=FALSE, warning=FALSE}


activos_tabla


```

\
\
\

# Seguimiento Stenotrophomonas maltophilia

```{r, echo=FALSE, message=FALSE, warning=FALSE}


indicador_marga_steno


```

\
\
\

# Seguimiento Enterobacter 

```{r, echo=FALSE, message=FALSE, warning=FALSE}


indicador_marga_enterobac


```

\
\
\

# Seguimiento Pseudomonas aeruginosa 

```{r, echo=FALSE, message=FALSE, warning=FALSE}


indicador_marga_pseudomona



```

\
\
\

# Seguimiento SARM 

```{r, echo=FALSE, message=FALSE, warning=FALSE}


indicador_marga_sarm



```

\
\
\

# Aislamientos finalizados en los últimos 20 días

```{r, echo=FALSE, message=FALSE, warning=FALSE}


finalizados_tabla

```


\
\
\

# Revisar habitaciones

```{r, echo=FALSE, message=FALSE, warning=FALSE}


habitas_por_mirar

```

