---
title: "ndm"
output: html_document
date: "2022-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, warning=FALSE}
#SCRIPT PARA informe de centinela, JUNIO 2022---------------------------------

library(pacman)
library(tidyverse)
library(gtsummary)
library(lubridate)
library(flextable)
library(ggplot2)
library(readxl)
library(writexl)
library(janitor)
library(readxlsb)
library(openxlsx)
library(skimr)
library(rio)
library(purrr)
library(RODBC)
library(gt)
#library(ggpubr)
#library(kableExtra)
library(knitr)
#library(devtools)
library(jpeg)
library(ggpubr)

gt_tabla <- function(tbl){
   tbl %>% 
    gt()%>% 
  #añadir bordes
  tab_style(
   style =  cell_borders(
      sides = c("left", "right", "top", "bottom"),
      color = "black",
      style = "solid"),
   locations = cells_body(
     columns = everything())) %>% 
  #enfatizar las titulos
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style     = list(
      #Give a thick border below
      cell_borders(sides = "bottom", weight = px(3)),
      #Make text bold
      cell_text(weight = "bold"))) %>% 
  opt_table_font(
        font = list(
          google_font("Chivo"),
          default_fonts()
        )
      ) 
}
```


```{r, include=FALSE, warning=FALSE}
#CAMBIOS MANUALES
# poner el primer dia de la semana a analizar
l_1 <- Sys.Date() - weeks(2) 

limite <- floor_date(l_1,
                     unit = "week",
                     week_start = 1) - 6 

#limite <- "2022-06-05"-----------por si se quiere ponerla semana  manualmente

#CARGAR DATOS------------------------------------------------------------------------------------

setwd("S:/Medicina Preventiva/AISLAMIENTOS TRABAJADOS/RECEPCION AISLAMIENTOS/Informes centinela")

#con <- odbcConnectAccess("S:/Medicina Preventiva/CENTINELA/CENTINela.MDB")

#table_names <- sqlTables(con) %>% select(TABLE_NAME)


#vigilancia_tables <- table_names %>% 
 # filter(grepl("koldo", TABLE_NAME)) %>% 
  #unlist()

#data <- vigilancia_tables %>% 
 # set_names() %>% 
 # map(.f = ~ sqlFetch(channel = con,
    #                  sqtable = .x)) %>% 
  #reduce(left_join, by = "GlobalRecordID") %>% 
  
data <- import("excel_limpio.xlsx" )  %>% 
  clean_names() %>% 
  as_tibble() 

# ME QUEDO CON LOS DE LA SEMANA ANTERIOR--------------------------------------------------------
data_limpio <-  data %>% 
  
  mutate(
    across(.cols = where(is.POSIXct), .fns = as.Date),
    
    edad = ((Sys.Date()- fecha_de_nacimiento)/365),
    edad_numeric = as.numeric(edad),
    edad_categorias = case_when(
      edad_numeric                      <  10  ~ "00-09",
      edad_numeric > 9 & edad_numeric < 20 ~ "10-19",
      edad_numeric > 19 & edad_numeric < 30 ~ "20-29",
      edad_numeric > 29 & edad_numeric < 40 ~ "30-39",
      edad_numeric > 39 & edad_numeric < 50 ~ "40-49",
      edad_numeric > 49 & edad_numeric < 60 ~ "50-59",
      edad_numeric > 59 & edad_numeric < 70 ~ "60-69",
      edad_numeric > 69 & edad_numeric < 80 ~ "70-79",
      edad_numeric > 79 & edad_numeric < 90 ~ "80-89",
      edad_numeric > 89 ~ ">90"),
    
    edad_categorias = factor(
      edad_categorias,
      level = c("00-09", "10-19", "20-29",
                "30-39", "40-49", "50-59",
                "60-69","70-79", "80-89",
                ">90")),
    
    
    #variables utiles: semana_nuevos y con LETRAS, AUTOMATICO-----------
    
    semana_nuevos = floor_date(fecha_inicio_aisl,
                               unit = "week",
                               week_start = 1),
    
    
    semana_nuevos_letras = floor_date(fecha_inicio_aisl,
                            unit = "week",
                            week_start = 1),
      
      
      
    semana_nuevos_letras_2 = floor_date(fecha_inicio_aisl,
                            unit = "week",
                            week_start = 1) + 6,
      
    semana_nuevos_letras = format( semana_nuevos_letras, "%d%b"),
    semana_nuevos_letras_2 = format( semana_nuevos_letras_2, "%d%b")) %>% 
    unite(col = "semana_nuevos_letras", c("semana_nuevos_letras", "semana_nuevos_letras_2"), sep = "/ ", remove = T) %>% 
     
  
  #----------------------------  
    mutate(   
    
    semana_final_aislamiento = floor_date(fecha_final_aisl,
                                          unit = "week",
                                          week_start = 1),
    
    dias_ingreso_registro =    fecha_registro    - fecha_de_ingreso,
    dias_ingreso_aislamiento = fecha_inicio_aisl - fecha_de_ingreso,
    
    #legibilidad
    
    germen = tolower(germen),
    germen = str_to_title(germen),
    
    precauciones = tolower(precauciones),
    precauciones = str_to_title(precauciones),
    
    sexo = case_when(
      sexo == 0 ~ "Hombre",
      sexo == 1 ~ "Mujer"),
    
    tipo  = case_when(
      tipo == 1 ~ "Nosocomial",
      tipo == 2 ~ "Comunitaria",
      tipo == 3 ~ "Reingreso nosocomial",
      tipo == 4 ~ "Incierto",
      tipo == 5 ~ "Reingreso comunitaria",
      tipo == 6 ~ "Asociada a cuidados"),
    
    id_procedencia = case_when(
      id_procedencia ==    1  ~	"ANESTESIA REANIMACIÓN",
      id_procedencia ==    2  ~	"C. INF. SECCIÓN ORTOPEDIA",
      id_procedencia ==    3  ~	"C.INF. SECCIÓN UROLÓGIA",
      id_procedencia ==    4  ~	"C. CARDIACA",
      id_procedencia ==    5  ~	"C.GENERAL A",
      id_procedencia ==    6  ~	"C. GENERAL B",
      id_procedencia ==    7  ~	"C. INF. SECCIÓN A",
      id_procedencia ==    8  ~	"C. INF. SECCIÓN B",
      id_procedencia ==    9  ~	"C. INF. SECCIÓN C",
      id_procedencia ==    10 ~	"C. INF. SECCIÓN ORL",
      id_procedencia ==    11 ~ "C. MAXILOFACIAL",
      id_procedencia ==    12 ~	"C. PLÁSTICA",
      id_procedencia ==    13 ~	"C. PLÁSTICA - G. QUEMADOS",
      id_procedencia ==    14 ~	"C. TORÁCICA",
      id_procedencia ==    15 ~	"C. VASCULAR",
      id_procedencia ==    16 ~	"CARDIOLOGÍA",
      id_procedencia ==    17 ~	"CARDIOLOGÍA INFANTIL",
      id_procedencia ==    18 ~	"ENDOCRINOLOGÍA",
      id_procedencia ==    19 ~	"GASTROENTEROLOGÍA",
      id_procedencia ==    20 ~	"GINECOLOGÍA",
      id_procedencia ==    21 ~	"GINECOLOGÍA - ONCOLOGÍA",
      id_procedencia ==    22 ~	"HEMATOLOGÍA",
      id_procedencia ==    23 ~	"M. INTERNA",
      id_procedencia ==    24 ~	"M. INTENSIVA",
      id_procedencia ==    25 ~	"NEFROLOGÍA",
      id_procedencia ==    26	~"NEFROLOGÍA INFANTIL",
      id_procedencia ==    27 ~	"NEUMOLOGÍA",
      id_procedencia ==    28 ~	"NEUROCIRUGÍA",
      id_procedencia ==    29 ~	"NEUROLOGÍA",
      id_procedencia ==    30	~"NEUROPEDIATRÍA",
      id_procedencia ==    31 ~	"O.R.L.",
      id_procedencia ==    32 ~	"OBSTETRICIA",
      id_procedencia ==    33 ~	"OFTALMOLOGÍA",
      id_procedencia ==    34 ~	"ONCOLOGÍA INFANTIL",
      id_procedencia ==    35 ~	"ONCOLOGÍA MÉDICA",
      id_procedencia ==    36 ~	"ONCOLOGÍA RADIOTERÁPICA",
      id_procedencia ==    37 ~	"PEDIATRÍA CUIDADOS INTENSIVOS",
      id_procedencia ==    38 ~	"PEDIATRÍA GENERAL",
      id_procedencia ==    39 ~	"PSIQUIATRÍA",
      id_procedencia ==    40	~ "PSIQUIATRÍA INFANTIL",
      id_procedencia ==    41 ~	"REHABILITACIÓN",
      id_procedencia ==    42	~ "REUMATOLOGÍA",
      id_procedencia ==    43	~ "TRAUMATOLOGÍA",
      id_procedencia ==    44	~ "U. ENF. INFECCIOSAS",
      id_procedencia ==    45	~ "UNIDAD CORONARIA",
      id_procedencia ==    46	~ "UNIDAD NEONATAL",
      id_procedencia ==    47 ~	"UROLOGÍA",
      id_procedencia ==    48	~ "U.C.HEPATICA",
      id_procedencia ==    49	~ "URGENCIAS MEDICO-QUIRURGICAS",
      id_procedencia ==    50 ~	"EXTRAHOSPITALARIO",
      id_procedencia ==    51 ~	"HOSPITALARIO",
      id_procedencia ==    52 ~	"REINGRHOSPITALARIO",
      id_procedencia ==    53 ~	"REINGREXTRAHOSPITALARIO"))%>% 
      
  mutate_if(is.numeric, round, digits=0) %>% 
  
  #quitamos covid que genera ruido
    filter(
           germen != "Coronavirus Sars-Cov-2" &
           germen != "Coronavirus Ciclos Tardíos" & 
           germen != "Coronavirus Contacto Estrecho" & 
           germen != "Adenovirus" &
           germen != "Astrovirus" &
           germen != "Bocavirus" &
           germen != "Coronavirus" &
           germen != "Coxsackie" &
           germen != "Echovirus" &
           germen != "Enterovirus" &
           germen != "Herpes Simplex I" &
           germen != "Herpes Simplex Ii" &
           germen != "Herpes Zoster" &
           germen != "Metapneumovirus" &
           germen != "Monkeypox" &
           germen != "Norovirus"&  
           germen != "Parechovirus"&
           germen != "Parvovirus B19"&
           germen != "Rabia Virus"&
           germen != "Rhinovirus"&
           germen != "Rotavirus"&
           germen != "Varicela-Zoster") %>% 
  
  filter(!grepl("Influenza|Parainfluenza|Virus|Vrs", germen)) %>% 
         #germen != "Influenza A" |
         #germen !=  grepl("Parainfluenza", germen) |
         #germen !grepl("Virus", germen) |
         #germen !=  grepl("Vrs", germen)) %>% 
  
  select(-c(orden, edad, fecha_de_nacimiento, no_ha_ca, conexion)) %>% 
  arrange(germen) %>% 
  mutate(fecha_germen_copia = fecha_germen - 4,
  
  #donde colonizo
    
    #across(starts_with("fechab"), as.Date, ~ . - 1),
         habitacion_muestra = case_when(
           #is.na(idhab2)                                                     ~ as.character(id_habitacion,
           
           fecha_germen >= fechab  ~ as.character(id_habitacion),
           
           fecha_germen < fechab  & fecha_germen >= fechab2 & !is.na(idhab2) ~ as.character(idhab2),
           fecha_germen < fechab  & fecha_germen >= fechab2 & is.na(idhab2) ~ as.character(id_habitacion),
           
           
           fecha_germen < fechab2  & fecha_germen >= fechab3 & !is.na(idhab3) ~ as.character(idhab3),
           fecha_germen < fechab2  & fecha_germen >= fechab3 & is.na(idhab3) & !is.na(idhab2) ~ as.character(idhab2),
           fecha_germen < fechab2  & fecha_germen >= fechab3 & is.na(idhab3) & is.na(idhab2) ~ as.character(id_habitacion),
           
           fecha_germen < fechab3  & fecha_germen >= fechab4 & !is.na(idhab4) ~ as.character(idhab4),
           fecha_germen < fechab3  & fecha_germen >= fechab4 & is.na(idhab4) & !is.na(idhab3) ~ as.character(idhab3),
           fecha_germen < fechab3  & fecha_germen >= fechab4 & is.na(idhab4) & is.na(idhab3) & !is.na(idhab2) ~ as.character(idhab2),
           fecha_germen < fechab3  & fecha_germen >= fechab4 & is.na(idhab4) & is.na(idhab3) &  is.na(idhab2) ~ as.character(id_habitacion),
           
           fecha_germen < fechab4  & fecha_germen >= fechab5 & !is.na(idhab5) ~ as.character(idhab5),
           fecha_germen < fechab4  & fecha_germen >= fechab5 & is.na(idhab5) & !is.na(idhab4) ~ as.character(idhab4),
           fecha_germen < fechab4  & fecha_germen >= fechab5 & is.na(idhab5) & is.na(idhab4) & !is.na(idhab3) ~ as.character(idhab3),
           fecha_germen < fechab4  & fecha_germen >= fechab5 & is.na(idhab5) & is.na(idhab4) &  is.na(idhab3) &  !is.na(idhab2) ~ as.character(idhab2),
           fecha_germen < fechab4  & fecha_germen >= fechab5 & is.na(idhab5) & is.na(idhab4) &  is.na(idhab3) &  is.na(idhab2) ~ as.character(id_habitacion),
           
           fecha_germen < fechab5  & fecha_germen >= fechab4 & !is.na(idhab6) ~ as.character(idhab6),
           fecha_germen < fechab5  & fecha_germen >= fechab4 & is.na(idhab6) & !is.na(idhab5) ~ as.character(idhab5),
           fecha_germen < fechab5  & fecha_germen >= fechab4 & is.na(idhab6) & is.na(idhab5) & !is.na(idhab4) ~ as.character(idhab4),
           fecha_germen < fechab5  & fecha_germen >= fechab4 & is.na(idhab6) & is.na(idhab5) &  is.na(idhab4) &  !is.na(idhab3) ~ as.character(idhab3),
           fecha_germen < fechab5  & fecha_germen >= fechab4 & is.na(idhab6) & is.na(idhab5) &  is.na(idhab4) &  is.na(idhab3) &  !is.na(idhab2) ~ as.character(idhab2),
           fecha_germen < fechab5  & fecha_germen >= fechab4 & is.na(idhab6) & is.na(idhab5) &  is.na(idhab4) &  is.na(idhab3) &  is.na(idhab2)  ~ as.character(id_habitacion),
           
           T ~ as.character(id_habitacion)
           ),

#LIMPIEZA DE LAS HABITACIONES
  
    habitacion_muestra_copia = habitacion_muestra,
    habitacion_muestra = gsub(pattern = "-", replacement = ".", habitacion_muestra, fixed = TRUE),
    habitacion_muestra = gsub(pattern = ",", replacement = ".", habitacion_muestra, fixed = TRUE),
    
    
    #las Ts son 33
    habitacion_muestra = gsub(pattern = "N", replacement = "22", habitacion_muestra, fixed = TRUE),
    habitacion_muestra = gsub(pattern = "C", replacement = "12", habitacion_muestra, fixed = TRUE),
    habitacion_muestra = gsub(pattern = "T", replacement = "33", habitacion_muestra, fixed = TRUE),
    habitacion_muestra = gsub(pattern = "M", replacement = "11", habitacion_muestra, fixed = TRUE),
    habitacion_muestra = gsub(pattern = "H", replacement = "14", habitacion_muestra, fixed = TRUE),
    
    #esto para las camas de la 650
    habitacion_muestra = gsub(pattern = "A", replacement = "12", habitacion_muestra, fixed = TRUE),
    habitacion_muestra = gsub(pattern = "B", replacement = "12", habitacion_muestra, fixed = TRUE),
    
    #y aqui ya lo convierto en numerico
    habitacion_muestra_planta = as.numeric(habitacion_muestra),
    
    
  habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68012, 680, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68112, 681, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68212, 682, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68312, 683, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68412, 684, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68512, 685, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68612, 686, habitacion_muestra_planta),
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 68712, 687, habitacion_muestra_planta),
   
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 65412, 654, habitacion_muestra_planta),
   
   
   habitacion_muestra_planta = if_else( habitacion_muestra_planta == 67612, 676, habitacion_muestra_planta)) %>% 
   
    #id_habitacion_planta = if_else(id_habitacion_planta > 70000, 0 , id_habitacion_planta)) %>% 
   
  
  #nombres de plantas
  mutate(
    cama = as.numeric(habitacion_muestra_planta),
    planta = case_when(
      cama > 99  & cama <121 ~ "1A",
      #las Ms
      cama > 1099  & cama <1150 ~ "1A",
      cama > 120 & cama <150 ~ "1B",
      #las Hs
      cama > 1399  & cama <1499 ~ "1A",
      cama > 149 & cama <175 ~ "1D",
      cama > 174 & cama <200 ~ "1E",
      cama > 199 & cama <221 ~ "2A",
      #las Ns
      cama > 2199  & cama <2250 ~ "2A",
      
      cama > 220 & cama <250 ~ "2B",
      cama > 249 & cama <275 ~ "2D",
      cama > 274 & cama <300 ~ "2E",
      cama > 299 & cama <322 ~ "3A",
      #las Ts
      cama > 3299  & cama <3350 ~ "3A",
      cama > 321 & cama <350 ~ "3B",
      cama > 349 & cama <375 ~ "3D",
      cama > 374 & cama <400 ~ "3E",
      cama > 399 & cama <425 ~ "4A",
      cama > 424 & cama <450 ~ "4B",
      cama > 449 & cama <475 ~ "4D",
      cama > 474 & cama <500 ~ "4E",
      
      
      cama > 499 & cama <512 ~ "Pasillo",
      cama > 511 & cama <517 ~ "GQx",
      cama > 520 & cama <535 ~ "UCI",
      
      cama > 534 & cama <549 ~ "Coro",
      #cama > 545 & cama <549 ~ "UCI",
      cama > 550 & cama <557 ~ "marti",
      cama > 549 & cama <575 ~ "5D",
      cama > 574 & cama <600 ~ "5E",
      
      
      cama > 600 & cama <614 ~ "R1",
      cama > 613 & cama <625 ~ "R2",
      cama > 633 & cama <642 ~ "RA",
      
      cama > 624 & cama <650 ~ "6B",
      cama > 649 & cama <675 ~ "6D",
      cama > 674 & cama <700 ~ "6E",
      cama > 699 & cama <750 ~ "7",
      cama > 1199 & cama <1250 ~ "12")) %>% 
  
  mutate(planta_bubble = case_when(
                                   planta == "12" ~ "12C",
                                   planta == "7" ~ "7C",
                                   planta == "UCI" ~ "6B",
                                   planta == "RA" ~ "6A",
                                   planta == "R1" ~ "6A",
                                   planta == "R2" ~ "6A",
                                   planta == "marti" ~ "5B",
                                   planta == "GQx" ~ "5B",
                                   planta == "Coro" ~ "5B",
                                   planta == "Pasillo" ~ "6A",
                                   T ~ as.character(planta))) %>%
  separate(planta_bubble, 
         into = c("piso", "planta_b"), 
         sep = "(?<=[0-9])(?=[A-Za-z])",
         remove = F) %>% 
  mutate(piso = as.numeric(piso))



```

```{r, include=FALSE, warning=FALSE}

img_2 <- readJPEG("criticos.jpg")

df <- data.frame (planta_b = c("A", "B", "C", 
                               "A", "B", "C", 
                               "A", "B", "C", 
                               "A", "B", "C", 
                               "A", "B", "C"),
                   piso  = c("1", "1", "1",
                            "2", "2", "2",
                            "3", "3", "3",
                            "4", "4", "4",
                            "5", "5", "5")) %>% 
  as_tibble() %>% 
  group_by(planta_b, piso) %>% 
  summarise(
    cuenta = n(),
    .groups = 'drop') %>% 
  mutate(cuenta = cuenta/100)





analisis_brote_1 <- function(tbl){
  
  tbl %>% 
  select(cic, 
         fecha_germen,
         id_habitacion:idhab6) %>% 
  gather("x", "hab", -c(cic,fecha_germen)) %>%
  select(-x) %>% 
  arrange(cic) %>% 
  mutate(
  hab = gsub(pattern = "-", replacement = ".", hab, fixed = TRUE),
    hab = gsub(pattern = ",", replacement = ".", hab, fixed = TRUE),
    
    
    #las Ts son 33
    hab = gsub(pattern = "N", replacement = "22", hab, fixed = TRUE),
    hab = gsub(pattern = "C", replacement = "12", hab, fixed = TRUE),
    hab = gsub(pattern = "T", replacement = "33", hab, fixed = TRUE),
    hab = gsub(pattern = "M", replacement = "11", hab, fixed = TRUE),
    hab = gsub(pattern = "H", replacement = "14", hab, fixed = TRUE),
    
    #esto para las camas de la 650
    hab = gsub(pattern = "A", replacement = "12", hab, fixed = TRUE),
    hab = gsub(pattern = "B", replacement = "12", hab, fixed = TRUE),
    
    #y aqui ya lo convierto en numerico
    hab_planta = as.numeric(hab),
    
    
  hab_planta = if_else( hab_planta == 68012, 680, hab_planta),
   hab_planta = if_else( hab_planta == 68112, 681, hab_planta),
   hab_planta = if_else( hab_planta == 68212, 682, hab_planta),
   hab_planta = if_else( hab_planta == 68312, 683, hab_planta),
   hab_planta = if_else( hab_planta == 68412, 684, hab_planta),
   hab_planta = if_else( hab_planta == 68512, 685, hab_planta),
   hab_planta = if_else( hab_planta == 68612, 686, hab_planta),
   hab_planta = if_else( hab_planta == 68712, 687, hab_planta),
   
   hab_planta = if_else( hab_planta == 65412, 654, hab_planta),
   
   
   hab_planta = if_else( hab_planta == 67612, 676, hab_planta)) %>% 
   
    #id_habitacion_planta = if_else(id_habitacion_planta > 70000, 0 , id_habitacion_planta)) %>% 
   
  
  #nombres de plantas
  mutate(
    cama = as.numeric(hab_planta),
    planta = case_when(
      cama > 99  & cama <121 ~ "1A",
      #las Ms
      cama > 1099  & cama <1150 ~ "1A",
      cama > 120 & cama <150 ~ "1B",
      #las Hs
      cama > 1399  & cama <1499 ~ "1A",
      cama > 149 & cama <175 ~ "1D",
      cama > 174 & cama <200 ~ "1E",
      cama > 199 & cama <221 ~ "2A",
      #las Ns
      cama > 2199  & cama <2250 ~ "2A",
      
      cama > 220 & cama <250 ~ "2B",
      cama > 249 & cama <275 ~ "2D",
      cama > 274 & cama <300 ~ "2E",
      cama > 299 & cama <322 ~ "3A",
      #las Ts
      cama > 3299  & cama <3350 ~ "3A",
      cama > 321 & cama <350 ~ "3B",
      cama > 349 & cama <375 ~ "3D",
      cama > 374 & cama <400 ~ "3E",
      cama > 399 & cama <425 ~ "4A",
      cama > 424 & cama <450 ~ "4B",
      cama > 449 & cama <475 ~ "4D",
      cama > 474 & cama <500 ~ "4E",
      
      
      cama > 499 & cama <512 ~ "Pasillo",
      cama > 511 & cama <517 ~ "GQx",
      cama > 520 & cama <535 ~ "UCI",
      
      cama > 534 & cama <549 ~ "Coro",
      #cama > 545 & cama <549 ~ "UCI",
      cama > 550 & cama <557 ~ "marti",
      cama > 549 & cama <575 ~ "5D",
      cama > 574 & cama <600 ~ "5E",
      
      
      cama > 600 & cama <614 ~ "R1",
      cama > 613 & cama <625 ~ "R2",
      cama > 633 & cama <642 ~ "RA",
      
      cama > 624 & cama <650 ~ "6B",
      cama > 649 & cama <675 ~ "6D",
      cama > 674 & cama <700 ~ "6E",
      cama > 699 & cama <750 ~ "7",
      cama > 1199 & cama <1250 ~ "12"),
    
    planta_mapa = case_when(
      planta == "marti" ~ "1A",
      planta == "UCI" ~ "3B",
      planta == "GQx" ~ "3A",
      planta == "Pasillo" ~ "2B",
      planta == "R1" ~ "5B",
      planta == "R2" ~ "5A",
      planta == "RA" ~ "5C",
      T ~ "otros"
      
    )) 
  
}

analisis_brote_2 <- function(tbl){
  
  tbl %>% 
  filter(planta_mapa != "otros")  %>%
    
  separate(planta_mapa, 
         into = c("piso", "planta_b"), 
         sep = "(?<=[0-9])(?=[A-Za-z])",
         remove = F) %>% 
    
  mutate(piso = as.numeric(piso)) %>% 
  group_by(planta_b, piso) %>% 
  summarise(
    cuenta = n(),
    .groups = 'drop') %>% 
    
    rbind(df) %>% 
    
    group_by(planta_b, piso) %>% 
  summarise(
    cuenta = sum(cuenta),
    .groups = 'drop') 

}


bubble_plot_criticos <- function(tbl) {
  
  tbl %>% 
    ggplot(aes(x = piso, y = planta_b)) +
    #theme(panel.grid.major = element_line(colour = "black"))+

    background_image(img_2) +
    geom_point(
      aes(fill = cuenta, size = cuenta), shape = 21
    ) +
    theme_minimal() +
    theme(
      legend.position = 'bottom',
      text = element_text(color = 'grey40')
    ) +
    guides(
      col = guide_none(),
      size = guide_none(),
      fill = guide_colorbar(
        barheight = unit(0.5, 'cm'),
        barwidth = unit(10, 'cm'),
        title.position = 'top'
      )
    ) +
    scale_size_area(max_size = 20) +
    scale_color_viridis_b(
      na.value = 'grey80'
    ) +
    scale_fill_viridis_c(option = "plasma",
      na.value = 'grey80') +
     
  geom_hline(yintercept = 1.5, col = "blue") +
  geom_hline(yintercept = 2.5, col = "blue") +
  geom_vline(xintercept = 1.5, col = "blue") +
  geom_vline(xintercept = 2.5, col = "blue") +
  geom_vline(xintercept = 3.5, col = "blue") +
  geom_vline(xintercept = 4.5, col = "blue") +
 
  
  theme(
    legend.title = element_text(size=12, face="bold"),
    axis.title = element_text(size=12, face="bold"), 
    plot.title = element_text(hjust=0,size=14,face="bold"),  
    plot.caption = element_text(hjust = 0, face = "italic")) 

  
}

```

```{r, include=FALSE, warning=FALSE}


ndm <- data_limpio %>% 
  filter(germen == "Klebsiela Pneumonia (Productor De Blea)",
         fecha_germen > "2020-12-31",
         tipo == "Nosocomial") %>% 
  analisis_brote_1() %>% 
  analisis_brote_2() %>% 
  bubble_plot_criticos() +
  labs(title = "Colonizaciones de Enterobacter productor de carbapenemasas de clase B (NDM)",
       subtitle = "",
       x = element_blank(),
       y = element_blank(),
       fill = 'Gradiente de casos') 

```



```{r, include=FALSE, warning=FALSE}
ndm_enero_junio <- data_limpio %>% 
  filter(germen == "Enterobacter Productor De Carbapenemasas",
         fecha_germen > "2021-12-31",
         fecha_germen < "2022-07-01"
         ) %>% 
  analisis_brote_1() %>% 
  analisis_brote_2() %>% 
  bubble_plot_criticos() +
  labs(title = "Colonizaciones de Enterobacter productor de carbapenemasas de clase B (NDM), enero a junio de 2022",
       subtitle = "",
       x = element_blank(),
       y = element_blank(),
       fill = 'Gradiente de casos') 

```

```{r, fig.align="center", echo = FALSE, fig.width = 15, fig.height = 10}
ndm

```

```{r, fig.align="center", echo = FALSE, fig.width = 15, fig.height = 10}

ndm_enero_junio

```

# 2021

```{r, include=FALSE, warning=FALSE}
ndm_2021 <- data_limpio %>% 
  filter(germen == "Enterobacter Productor De Carbapenemasas",
         fecha_germen > "2020-12-31",
         fecha_germen < "2021-12-31"
         ) %>% 
  analisis_brote_1() %>% 
  analisis_brote_2() %>% 
  bubble_plot_criticos() +
  labs(title = "Colonizaciones de Enterobacter productor de carbapenemasas de clase B (NDM), 2021",
       subtitle = "",
       x = element_blank(),
       y = element_blank(),
       fill = 'Gradiente de casos') 
```


```{r, fig.align="center", echo = FALSE, fig.width = 15, fig.height = 10}

ndm_2021

```

# 2022

```{r, include=FALSE, warning=FALSE}

ndm_2022 <- data_limpio %>% 
  filter(germen == "Enterobacter Productor De Carbapenemasas",
         fecha_germen > "2021-12-31",
         fecha_germen < "2022-12-31"
         ) %>% 
  analisis_brote_1() %>% 
  analisis_brote_2() %>% 
  bubble_plot_criticos() +
  labs(title = "Colonizaciones de Enterobacter productor de carbapenemasas de clase B (NDM), 2022",
       subtitle = "",
       x = element_blank(),
       y = element_blank(),
       fill = 'Gradiente de casos') 
```


```{r, fig.align="center", echo = FALSE, fig.width = 15, fig.height = 10}

ndm_2022

```

```{r, include=FALSE, warning=FALSE}
RODBC::odbcClose(con)

```

